version: '3.8'

services:
  prospectpredictor:
    image: prospectpredictor
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:  
      - 8000:5000

  web:
    build: nginx
    ports:
      - "80:80"




